import streamlit as st
from supabase import create_client, Client

# Initialize Connection
def init_supabase():
    url = st.secrets["SUPABASE_URL"]
    key = st.secrets["SUPABASE_KEY"]
    return create_client(url, key)

def save_matches_to_db(matches_df):
    """Saves the generated matches into Supabase"""
    supabase = init_supabase()
    
    # Convert DataFrame to list of dictionaries for insertion
    rows_to_insert = []
    for _, row in matches_df.iterrows():
        rows_to_insert.append({
            "emp_id": str(row['Giver_ID']), # Ensure string
            "name": row['Giver_Name'],
            "email": row['Giver_Email'],
            "location": row['Location'],
            "match_name": row['Receiver_Name'],
            "match_email": row['Receiver_Email'],
            "match_location": row['Location'],
            # secret_token is auto-generated by Supabase (default uuid)
            # is_revealed is false by default
        })
    
    # Insert data
    response = supabase.table('participants').insert(rows_to_insert).execute()
    return response.data

def get_user_by_token(token):
    """Fetch user data using the magic link token"""
    supabase = init_supabase()
    try:
        response = supabase.table('participants').select("*").eq('secret_token', token).execute()
        # If we found a user, return the first result
        if response.data and len(response.data) > 0:
            return response.data[0]
        return None
    except Exception as e:
        return None

def mark_as_revealed(token):
    """Update the database to say the user opened their gift"""
    supabase = init_supabase()
    supabase.table('participants').update({'is_revealed': True}).eq('secret_token', token).execute()

def submit_survey(token, gift_pref, expected_santa):
    """Saves the user's survey answers and marks survey as complete"""
    supabase = init_supabase()
    supabase.table('participants').update({
        'gift_preference': gift_pref,
        'expected_santa': expected_santa,
        'survey_completed': True
    }).eq('secret_token', token).execute()

def get_target_preferences(target_email):
    """
    Fetch the wishlist of the person you are gifting to.
    (So the Giver can see what the Receiver wants)
    """
    supabase = init_supabase()
    response = supabase.table('participants').select("gift_preference").eq('email', target_email).execute()
    if response.data and len(response.data) > 0:
        return response.data[0].get('gift_preference', "No preference listed yet.")
    return "No preference listed yet."